apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxnginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fluxnginx
  template:
    metadata:
      labels:
        app: fluxnginx
    spec:
      containers:
      - name: fluxnginx
        image: nginx:latest
        ports:
        - containerPort: 80
