apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-fluxkustomization
  namespace: devops-test
spec:
  interval: 2m # Interval to check for changes
  path: ./ # Path to the folder in your repo containing the Kubernetes manifests
  prune: true # Automatically clean up resources that are no longer present
  sourceRef:
    kind: GitRepository
    name: flux-gitrepo

